---
title: Peticiones de información de los grupos auditores del Ayuntamiento de Madrid
output:
  html_document:
    toc: false
    toc_float: false
    includes:
      before_body: doc_prefix_index.html
---


```{r setup, include=F}
## Global options
options(digits = 4, scipen=10)
knitr::opts_chunk$set(echo=F, cache=F, prompt=F, tidy=T, comment=NA, message=F, warning=F)
```

```{r}
# CARGA DE DATOS
library(airtabler)
library(dplyr)
library(plotly)
Sys.setenv(AIRTABLE_API_KEY="keyZOgDPeLEn3Me8q")
datos <- airtable(base = "appe7uLXI2oMZ033Y", tables = c("Peticiones", "Respuestas", "Distritos", "Fichas ilegitimidad"))
datos.peticiones <- datos$Peticiones$select()
datos.respuestas <- datos$Respuestas$select()
datos.distritos <- datos$Distritos$select()

# PREPOCESAMIENTO DE DATOS
datos.peticiones$id <- NULL
datos.respuestas$id <- NULL
datos.peticiones$createdTime <- NULL
datos.respuestas$createdTime <- NULL
datos.distritos$createdTime <- NULL
datos.peticiones$Distrito <- unlist(datos.peticiones$Distrito)
# Fusionar tabla de peticiones con tabla de distritos
datos.peticiones <- left_join(datos.peticiones, datos.distritos[c("id","Nombre")], by=c("Distrito"="id"))
datos.peticiones$Distrito <- NULL
datos.peticiones <- rename(datos.peticiones, Distrito=Nombre)
datos.peticiones$Distrito <- as.factor(datos.peticiones$Distrito)
# Fusionar tabla de peticiones con tabla de respuestas
datos.peticiones <- left_join(datos.peticiones, datos.respuestas, by="Registro")
# Convertir las fechas a tipo date
datos.peticiones$`Fecha envío` <- as.Date(datos.peticiones$`Fecha envío`, "%Y-%m-%d")
datos.peticiones$`Fecha respuesta` <- as.Date(datos.peticiones$`Fecha respuesta`, "%Y-%m-%d")
# Cambiar respuesta NA por "No conestatas"
datos.peticiones$`Valoración respuesta`[is.na(datos.peticiones$`Valoración respuesta`)] <- "Sin respuesta"
```

### Número total de peticiones: `r nrow(datos.peticiones)`


```{r}
library(DT)
crear.url <- function(enlace, texto) {
  return(paste0('<a href="peticion-', gsub("/", "-", enlace) , '.html">',  texto, '</a>'))
}

peticiones <- rename(datos.peticiones, temp=Título) %>% 
  mutate(Título=crear.url(Registro, temp)) %>%
  select(Registro, Distrito, `Fecha envío`, Título) %>%
  arrange(`Fecha envío`) 

datatable(peticiones, rownames = F, escape=F, filter = 'bottom', options = list(pageLength = 5, dom="ltip", language = list(url = 'http://cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')))
```


```{r}
time <- datos.peticiones$`Fecha respuesta` - datos.peticiones$`Fecha envío`
```
## Tiempo medio de respuesta: `r mean(as.numeric(time),na.rm=T)` días


## Valoración de las respuestas

```{r valoracion_respuestas}
# Diagrama de sectores de la valoración de las respuestas
datos.valoraciones <- datos.peticiones %>% group_by(`Valoración respuesta`) %>% summarise(Freq=n())
xaxis <- list(showgrid=F, zeroline=F, showticklabels = F)
yaxis <- list(showgrid=F, zeroline=F, showticklabels = F)
p <- plot_ly(datos.valoraciones, labels = ~`Valoración respuesta`, values = ~Freq, type = 'pie', textposition = 'none', direction="clockwise") %>%
  layout(xaxis=xaxis, yaxis=yaxis, showlegend=T, legend=list(x = 1, y = 0.5), margin=list(r=0))
p
```



